// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockMate.Api.Data;

#nullable disable

namespace MockMate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250713083455_AddQuestionToJournalEntry")]
    partial class AddQuestionToJournalEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("MockMate.Api.Models.InterviewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("UserAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "QuestionId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("MockMate.Api.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reflection")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Category");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("MockMate.Api.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int?>("QuestionCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SampleAnswer")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tips")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Difficulty");

                    b.HasIndex("IsActive");

                    b.HasIndex("QuestionCategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Leadership",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "I was leading a software development team when our main client changed requirements halfway through the project. I called an emergency team meeting, reassigned tasks based on new priorities, and implemented daily check-ins to ensure we stayed on track. The project was delivered on time and the client was satisfied with the final product.",
                            Tags = "leadership,team-management,project-management,decision-making",
                            Text = "Tell me about a time when you had to lead a team through a difficult project.",
                            Tips = "Focus on your specific actions as a leader. Mention how you communicated with the team, made decisions, and ensured project success.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Leadership",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Advanced",
                            IsActive = true,
                            SampleAnswer = "During my internship, our team leader was absent when a critical bug was discovered in production. I had to decide whether to roll back the deployment or attempt a quick fix. I gathered input from senior developers, assessed the risks, and chose to implement a targeted fix while preparing a rollback plan. The fix was successful and prevented major downtime.",
                            Tags = "decision-making,leadership,problem-solving,risk-assessment",
                            Text = "Describe a situation where you had to make a difficult decision without all the information you needed.",
                            Tips = "Emphasize your decision-making process, how you gathered available information, and the rationale behind your choice.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Leadership",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Advanced",
                            IsActive = true,
                            SampleAnswer = "I needed to convince a colleague from another department to prioritize our shared project. I scheduled a meeting to understand their concerns, presented data showing the project's impact on both departments, and proposed a solution that would benefit their team as well. They agreed to prioritize the project and we successfully completed it together.",
                            Tags = "influence,persuasion,cross-functional,collaboration",
                            Text = "Give me an example of when you had to influence someone without having authority over them.",
                            Tips = "Show how you used persuasion skills, data, and mutual benefits rather than authority to influence others.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Teamwork",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "I was working on a group project with someone who was consistently late to meetings and missed deadlines. I scheduled a private conversation to understand their challenges and discovered they were struggling with time management. I offered to help them create a task breakdown and we established regular check-ins. Their performance improved significantly.",
                            Tags = "teamwork,conflict-resolution,communication,mentoring",
                            Text = "Tell me about a time when you had to work with a difficult team member.",
                            Tips = "Focus on how you approached the situation professionally and found constructive solutions rather than just complaining about the person.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Teamwork",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Beginner",
                            IsActive = true,
                            SampleAnswer = "During a university hackathon, I worked with students from business, design, and engineering backgrounds. Initially, we struggled with communication as we all had different perspectives. I suggested we start by sharing our expertise and creating a common vocabulary. This helped us combine our diverse skills to create an innovative solution that won second place.",
                            Tags = "collaboration,diversity,cross-functional,communication",
                            Text = "Describe a time when you had to collaborate with people from different backgrounds or departments.",
                            Tips = "Highlight how you bridged differences and leveraged diverse perspectives as strengths rather than obstacles.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Problem Solving",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "Our e-commerce website was experiencing slow loading times during peak hours. I analyzed server logs, identified database queries as the bottleneck, and discovered several unoptimized queries. I implemented query optimization, added database indexing, and introduced caching. The page load time improved by 60% and customer satisfaction increased.",
                            Tags = "problem-solving,analytical-thinking,technical-skills,optimization",
                            Text = "Tell me about a complex problem you solved and how you approached it.",
                            Tips = "Walk through your systematic approach: problem identification, analysis, solution development, and results measurement.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Problem Solving",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Advanced",
                            IsActive = true,
                            SampleAnswer = "Our team needed to reduce software licensing costs but couldn't compromise functionality. Instead of cutting features, I researched open-source alternatives and proposed a hybrid approach using both commercial and open-source tools. I created a migration plan and led the implementation, resulting in 40% cost savings while maintaining all required functionality.",
                            Tags = "creativity,innovation,cost-reduction,strategic-thinking",
                            Text = "Describe a time when you had to think outside the box to solve a problem.",
                            Tips = "Emphasize your creative thinking process and how your unconventional approach delivered better results than traditional solutions.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Conflict Resolution",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Advanced",
                            IsActive = true,
                            SampleAnswer = "My manager wanted to rush a product release, but I believed it needed more testing. I prepared a presentation with data showing potential risks and customer impact. I proposed a compromise: release to a limited beta group first. My manager agreed, and we discovered critical bugs that would have affected thousands of users. The full release was successful after addressing these issues.",
                            Tags = "conflict-resolution,communication,data-driven,advocacy",
                            Text = "Tell me about a time when you disagreed with your manager or supervisor.",
                            Tips = "Show respect for authority while demonstrating your ability to advocate for what you believe is right using data and professional communication.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Conflict Resolution",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "Two team members disagreed about the technical approach for a project feature. I organized a meeting where each person presented their solution. I facilitated a discussion focusing on project requirements and asked clarifying questions. We identified that both approaches had merits and combined them into a hybrid solution that satisfied both team members and project needs.",
                            Tags = "mediation,teamwork,technical-discussion,facilitation",
                            Text = "Describe a situation where you had to mediate between conflicting team members.",
                            Tips = "Focus on your role as a neutral facilitator and how you helped the team find a collaborative solution.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Adaptability",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Beginner",
                            IsActive = true,
                            SampleAnswer = "I was assigned to a project requiring knowledge of React, which I had never used before. I immediately started with online tutorials, built small practice projects, and sought mentorship from experienced React developers. Within two weeks, I was contributing effectively to the project and even suggested improvements to our component structure.",
                            Tags = "learning-agility,adaptability,self-development,technology",
                            Text = "Tell me about a time when you had to quickly learn something new to complete a project.",
                            Tips = "Demonstrate your learning agility and proactive approach to acquiring new skills under pressure.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Adaptability",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "I was working on a long-term research project when my manager asked me to immediately support a critical client issue. I quickly documented my current progress, created a transition plan, and shifted focus to the urgent issue. I solved the client problem within 24 hours and then efficiently resumed my research project without losing momentum.",
                            Tags = "flexibility,prioritization,time-management,client-service",
                            Text = "Describe a time when priorities changed suddenly and how you handled it.",
                            Tips = "Show how you can pivot quickly while maintaining organization and not losing sight of your original responsibilities.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Achievement",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Beginner",
                            IsActive = true,
                            SampleAnswer = "During my internship, I automated a manual reporting process that was taking 8 hours per week. I analyzed the current workflow, designed a solution using Python scripts, and implemented automated data collection and report generation. This saved the team 32 hours per month and reduced errors by 95%. The solution is still being used today.",
                            Tags = "achievement,automation,efficiency,impact,innovation",
                            Text = "Tell me about your greatest professional achievement.",
                            Tips = "Choose an achievement that demonstrates measurable impact and showcases skills relevant to the role you're applying for.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Achievement",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "I set a goal to become a certified cloud solutions architect within six months while working full-time. I created a study schedule, joined online study groups, and built hands-on projects to practice. I passed the certification exam on my first attempt and immediately applied my new knowledge to optimize our company's cloud infrastructure, resulting in 25% cost savings.",
                            Tags = "goal-setting,certification,self-improvement,cloud-computing",
                            Text = "Describe a goal you set for yourself and how you achieved it.",
                            Tips = "Demonstrate your goal-setting process, commitment to self-improvement, and how you applied your achievement to create value.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Achievement",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = "Intermediate",
                            IsActive = true,
                            SampleAnswer = "I was asked to create a simple customer feedback form, but I noticed an opportunity to implement a comprehensive feedback system. I designed a solution with real-time analytics, automated routing to relevant departments, and response tracking. The system increased customer satisfaction scores by 30% and is now used company-wide.",
                            Tags = "exceeding-expectations,innovation,customer-satisfaction,systems-thinking",
                            Text = "Tell me about a time when you exceeded expectations.",
                            Tips = "Show how you went beyond the minimum requirements and delivered additional value that had lasting impact.",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MockMate.Api.Models.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#3B82F6");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("QuestionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#8B5CF6",
                            Description = "Questions about leading teams, making decisions, and taking initiative",
                            IsActive = true,
                            Name = "Leadership",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10B981",
                            Description = "Questions about collaboration, communication, and working with others",
                            IsActive = true,
                            Name = "Teamwork",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            Description = "Questions about analytical thinking, creativity, and overcoming challenges",
                            IsActive = true,
                            Name = "Problem Solving",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#EF4444",
                            Description = "Questions about managing disagreements and difficult situations",
                            IsActive = true,
                            Name = "Conflict Resolution",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#3B82F6",
                            Description = "Questions about handling change, learning, and flexibility",
                            IsActive = true,
                            Name = "Adaptability",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#EC4899",
                            Description = "Questions about accomplishments, goals, and delivering results",
                            IsActive = true,
                            Name = "Achievement",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("MockMate.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyField")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("University")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MockMate.Api.Models.InterviewSession", b =>
                {
                    b.HasOne("MockMate.Api.Models.Question", "Question")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockMate.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MockMate.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("MockMate.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MockMate.Api.Models.Question", b =>
                {
                    b.HasOne("MockMate.Api.Models.QuestionCategory", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionCategoryId");
                });

            modelBuilder.Entity("MockMate.Api.Models.Question", b =>
                {
                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("MockMate.Api.Models.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
